### ISSUE TITLE
reconnect for local GSB endpoints

### ISSUE THREAD

**Issue by tworec** [golemfactory/ya-service-bus#16]
Related to https://github.com/golemfactory/yagna/issues/1140
and #13 
and #21

**Comment by mateuszsrebrny** [comment]
@mfranciszkiewicz should we close this issue now? with golemfactory/ya-service-bus#21 merged?

**Comment by tworec** [comment]
@maaktweluit pls report your issue with slow machine

**Comment by mfranciszkiewicz** [comment]
Local endpoints are now re-bound while reconnecting (via #21). However, we have isolated an issue where reconnecting never finishes, which will be reported and investigated separately.
