### ISSUE TITLE
ya-sb-router has a enormous memory footprint

### ISSUE THREAD

**Issue by etam** [golemfactory/ya-service-bus#20]
**Why**
After running for one week on production it uses about 10GB of memory.

**What**
 - [x] investigate what is causing high memory usage
 - [x] fix the problem(s)

**Comment by tworec** [comment]
mbenke — Yesterday at 08:32
> Tonight yagna ate >5G memory, I think the memory leak @etam  mentioned is real: 
`7773 root      20   0 5979556   5,6g  30172 R 100,0   2,2   1112:53 yagna  `
> Here's the log, which might be interesting of itself as many thing seem to go wrong
[yagna_rCURRENT.log](https://github.com/golemfactory/ya-service-bus/files/6312347/yagna_rCURRENT.log)
